### ISSUE TITLE
Custom global HotKeys

### ISSUE THREAD

**Issue by Fire-Whale** [dedpnd/yaradio-yamusic#29]
Thakns for your project.

Is it possible to add custom hotkeys here? Also would be great, if there will be global on/off switcher for them

**Comment by dedpnd** [comment]
Thank you for your interest.
I'll try to think about it.

**Comment by istarion** [comment]
My pain is global `ctrl+q` hotkey because I'm using it frequently in IDE and it kills yaradio app instantly (linux).

Before v1.0.0 I solved that problem by modifying /resources/app/public/modules/globalShortcut.js , but there are no zip releases for linux now, and I don't know how to change it in AppImage distribution.

**Comment by dedpnd** [comment]
@istarion It's really not fun :)

**Comment by zorgzerg** [comment]
Hi, what about `ctrl+q`. Application still close by pressing it (
